require('plugins')
require('options')
require('lualine-config')
require('bufferline-config')
require('nvim-tree-config')
require('treesitter-config')
require('autopairs-config')
require('keybindings')
require('whichkey-config')
require('telescope-config')
vim.cmd('colorscheme nord')

