require('plugins')
require('options')
require('lualine-config')
--require('bufferline-config')
require('nvim-tree-config')
--require('treesitter-config')
require('autopairs-config')
require('keybindings')
require('whichkey-config')
require('telescope-config')
require('colorizer-config')
require('lsp')
--require('ftplugin')
require('mason-lspconfig')
require('jaq-nvim-config')
require('code-runner-config')
require('vim-terminator-config')
vim.cmd('colorscheme tokyonight')
-- vim.g.tokyonight_style = "night"
