require('plugins')
require('options')
require('lualine-config')
require('bufferline-config')
require('nvim-tree-config')
--require('treesitter-config')
require('autopairs-config')
require('whichkey-config')
require('telescope-config')
require('colorizer-config')
require('conjure')
require('lsp')
require('mason-lspconfig')
require('jaq-nvim-config')
require('code-runner-config')
--require('vim-terminator-config')
require('keybindings')
require('devicons')
vim.cmd('colorscheme tokyonight')
-- vim.g.tokyonight_style = "night"
vim.g.sexp_filetypes="clojure,scheme,lisp,fennel,janet,racket"
